# Generated by Django 4.1.2 on 2022-10-09 21:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogo_fotos_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='users_views',
        ),
        migrations.AddField(
            model_name='album',
            name='users_permitions',
            field=models.ManyToManyField(related_name='users_permitions', to=settings.AUTH_USER_MODEL),
        ),
    ]
