# Generated by Django 4.0.4 on 2022-07-10 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_fotos_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumimage',
            name='tags',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo_fotos_app.album'),
        ),
    ]
