# Generated by Django 4.0.4 on 2022-07-14 23:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_fotos_app', '0002_albumimage_tags_alter_albumimage_album'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-creada']},
        ),
        migrations.AddField(
            model_name='albumimage',
            name='album_titulo',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
