# Generated by Django 4.1.2 on 2022-10-09 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo_fotos_app', '0002_remove_album_users_views_album_users_permitions'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='es_publico',
            field=models.BooleanField(default=False),
        ),
    ]
